Project1 replit assignment Part1 branch
BlueMarlinAudio/PFMCPP_Project1 pull request #1
Opened 2024-01-29 13:35 UTC by BlueMarlinAudio

Hi matkatmusic,
Did the branching out, named it 'Part1'. Did the 10 nouns, tried coming up with appropriate actions, wrote them out as identifiers.functions(); as you show in example. Finally, I checked my code and comments for formatting compliance vis a vis JUCE rules.

Slack username:

2024-01-30 19:32 UTC, matkatmusic requested changes

2024-01-30 19:32 UTC, matkatmusic commented on main.cpp
> +key.fiitingIntoKeyhole();
As explained in the instructions:
Here is the obligatory request for some changes to get you familiar with the Pull Request Review process.
REPLACE the highlighted noun/action as follows:
- [ ] come up with a new noun and 3 actions
- [ ] pick a noun that needs `camelCase` for the name
- [ ] pick actions that need `camelCase` for their name.

Do not create an 11th noun.

Once you have completed the above-requested changes, please do the following:
- click each checkbox to mark each requested change as completed.
- click the `[Resolve Conversation]` button.
- Re-request a review of your pull request. It's on the right side of the Pull request page where you originally requested my review.
- Send me the link to your pull request in a new message.

2024-01-31 11:05 UTC, BlueMarlinAudio commented on main.cpp
> +key.fiitingIntoKeyhole();
Did the new noun and three actions, on line 100 to 106. /Simon

2024-02-02 03:06 UTC, matkatmusic approved these changes

2024-02-02 03:06 UTC, merged